before_script:
  - export OMP_NUM_THREADS=1
  - ulimit -c 0
  - ulimit -a

variables:
  CI_DEBUG_TRACE: "true"

stages:
  - build
  - test

##### BUILD STAGE #####

### GNU compilers + MPICH + Netlib BLAS, LAPACK, ScaLAPACK ###
build.gnu:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - export PATH=$MPICH_HOME/bin/:$PATH
    - export LD_LIBRARY_PATH=$MPICH_HOME/lib:$LD_LIBRARY_PATH
    - cat ./toolchains/gnu.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/gnu.cmake ..
    - make -j4
  artifacts:
    when: always
    paths:
      - $CI_JOB_NAME/
    expire_in: 1 days

### GNU compilers + Spack-installed packages ###
build.spack:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/dla-future-external:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - export PATH=/spack-view/bin:$PATH
    - export LD_LIBRARY_PATH=/spack-view/lib/:$LD_LIBRARY_PATH
    - cat ./toolchains/spack.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../toolchains/spack.cmake ..
    - ninja -j4
  artifacts:
    when: always
    paths:
      - $CI_JOB_NAME/
    expire_in: 1 days

### NVIDIA HPC SDK (20.7) ###
build.nvhpc:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/centos-nvhpc:latest
  script:
    - cat ./toolchains/nvhpc.cmake
    - export LD_PRELOAD=/usr/lib64/libstdc++.so.6
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/nvhpc.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL ###
build.intel:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL (shared library) ###
build.intel-shared:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel.cmake -DBUILD_SHARED_LIBS=ON ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL Debug ###
build.intel-debug:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel_debug.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_debug.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL + external solver libraries ###
build.intel-external:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-elsi-external:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel_external.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_external.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL + external solver libraries for LLVM compilers ###
build.intel-external-llvm:
  stage: build
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-elsi-external:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel_external_llvm.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_external_llvm.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL + CUDA ###
build.intel-gpu:
  stage: build
  rules:
    - when: on_success
  tags:
    - node17.timewarp
  image:
    name: uthpalaherath/ubuntu20-intel2024.1-cuda11:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - nvidia-smi
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel_gpu.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel_gpu.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### Intel 2022 compilers + MPI + MKL + CUDA ###
build.intel2022-gpu:
  stage: build
  rules:
    - when: on_success
  tags:
    - node17.timewarp
  image:
    name: uthpalaherath/ubuntu20-intel2022-cuda11:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - nvidia-smi
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cat ./toolchains/intel2022_gpu.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -DCMAKE_TOOLCHAIN_FILE=../toolchains/intel2022_gpu.cmake ..
    - make -j4
  artifacts:
    paths:
      - $CI_JOB_NAME/
    when: always
    expire_in: 1 days

### GNU compilers + Spack-installed packages + CUDA ###
build.spack-cuda:
  stage: build
  rules:
    - when: on_success
  tags:
    - node17.timewarp
  image:
    name: uthpalaherath/dla-future-external-cuda:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - nvidia-smi
    - export PATH=/spack-view/bin:$PATH
    - export LD_LIBRARY_PATH=/spack-view/lib/:/spack-view/lib64:$LD_LIBRARY_PATH
    - cat ./toolchains/spack-cuda.cmake
    - rm -rf $CI_JOB_NAME
    - mkdir $CI_JOB_NAME
    - cd $CI_JOB_NAME
    - cmake -GNinja -DCMAKE_TOOLCHAIN_FILE=../toolchains/spack-cuda.cmake ..
    - ninja -j4
  artifacts:
    when: always
    paths:
      - $CI_JOB_NAME/
    expire_in: 1 days


##### TEST STAGE #####

### GNU compilers + MPICH + Netlib BLAS, LAPACK, ScaLAPACK ###
test.gnu:
  stage: test
  dependencies:
    - build.gnu
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - export PATH=$MPICH_HOME/bin/:$PATH
    - export LD_LIBRARY_PATH=$MPICH_HOME/lib:$LD_LIBRARY_PATH
    - cd build.gnu
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### GNU compilers + Spack-installed packages ###
test.spack:
  stage: test
  dependencies:
    - build.spack
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/dla-future-external:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - export PATH=/spack-view/bin:$PATH
    - export LD_LIBRARY_PATH=/spack-view/lib/:$LD_LIBRARY_PATH
    - cd build.spack
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### NVIDIA HPC SDK (20.7) ###
test.nvhpc:
  stage: test
  dependencies:
    - build.nvhpc
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/centos-nvhpc:latest
  script:
    - export LD_PRELOAD=/usr/lib64/libstdc++.so.6
    - cd build.nvhpc
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL ###
test.intel:
  stage: test
  dependencies:
    - build.intel
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL Debug ###
test.intel-debug:
  stage: test
  dependencies:
    - build.intel-debug
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel-debug
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL (shared library) ###
test.intel-shared:
  stage: test
  dependencies:
    - build.intel-shared
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-mpich3.3.2-gnu10.5:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel-shared
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL + external solver libraries ###
test.intel-external:
  stage: test
  dependencies:
    - build.intel-external
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-elsi-external:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel-external
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL + external solver libraries for LLVM compilers ###
test.intel-external-llvm:
  stage: test
  dependencies:
    - build.intel-external-llvm
  rules:
    - when: on_success
  tags:
    - docker
  image:
    name: uthpalaherath/ubuntu20-intel2022-elsi-external:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel-external-llvm
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel compilers + MPI + MKL + CUDA ###
test.intel-gpu:
  stage: test
  dependencies:
    - build.intel-gpu
  rules:
    - when: on_success
  tags:
    - node17.timewarp
  image:
    name: uthpalaherath/ubuntu20-intel2024.1-cuda11:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - nvidia-smi
    - source /opt/intel/oneapi/setvars.sh
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel-gpu
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### Intel 2022 compilers + MPI + MKL + CUDA ###
test.intel2022-gpu:
  stage: test
  dependencies:
    - build.intel2022-gpu
  rules:
    - when: on_success
  tags:
    - node17.timewarp
  image:
    name: uthpalaherath/ubuntu20-intel2022-cuda11:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - nvidia-smi
    - ulimit -s unlimited
    - export MKL_DYNAMIC=FALSE
    - export MKL_NUM_THREADS=1
    - cd build.intel2022-gpu
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days

### GNU compilers + Spack-installed packages + CUDA ###
test.spack-cuda:
  stage: test
  dependencies:
    - build.spack-cuda
  rules:
    - when: on_success
  tags:
    - node17.timewarp
  image:
    name: uthpalaherath/dla-future-external-cuda:latest
    entrypoint: [ '/bin/bash', '-c', 'ln -snf /bin/bash /bin/sh && /bin/bash -c $0' ]
  script:
    - nvidia-smi
    - export PATH=/spack-view/bin:$PATH
    - export LD_LIBRARY_PATH=/spack-view/lib/:/spack-view/lib64:$LD_LIBRARY_PATH
    - cd build.spack-cuda
    - ctest --output-on-failure
  artifacts:
    when: always
    expire_in: 1 days
